[package]
name = "avif"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
wasm-bindgen = "0.2"
avif-serialize = "0.8"
rav1e = { version = "0.6.6", default-features = false, features = ["wasm"] }

[profile.release]
opt-level = "s"
lto = true

[dev-dependencies]
jpeg-decoder = "0.3"
