[package]
name = "avif"
version = "0.5.0"
edition = "2021"

[lib]
crate-type = ["cdylib",'rlib']

[dependencies]
wasm-bindgen = "0.2"
avif-serialize = "0.8"
rav1e = { version = "0.7.1", default-features = false, features = ["wasm"] }

[profile.release]
debug = false
opt-level = "s"
lto = true
#panic = "abort"

[dev-dependencies]
jpeg-decoder = "0.3"
